print("Ardra")
print("Varun")
print("Adil")
print("Geo")
print("Anjana_S")
print("Sreevidya")
print("vivek")
print("Smera")
print("jyothirmayi")
print("Ihsana")
print("Swetha Benny")
print("Unnimaya")
print("Anna")
